name: Build website to container

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  CONTAINER_IMAGE: app
  CONTAINER_REPO: ${{ github.repository }}
  HUGO_VERSION: 0.116.1

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add various credentials
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Contain and Push
        run: bin/build
