# Page settings

relativeURLs = true
languageCode = "en-us"
title = 'Virsyne Website'

publishDir = "../public"

# Do not build files for websites. Need them? Set to false
disableRSS = true
# disableSitemap = true
# disable404 = true

[params]

# Meta
description = "Resume"
author = "Jin Chan"

[menu]
    [[menu.nav]]
    identifier = "home"
    name = "Home"
    url = "#home"
    weight = 1

    [[menu.nav]]
    identifier = "resume"
    name = "About"
    url = "#about"
    weight = 2

    [[menu.nav]]
    identifier = "skills"
    name = "Skills"
    url = "#skills"
    weight = 3

    [[menu.nav]]
    identifier = "experience"
    name = "Experience"
    url = "#experience"
    weight = 4

    [[menu.nav]]
    identifier = "project"
    name = "Projects"
    url = "#project"
    weight = 4

    [[menu.nav]]
    identifier = "education"
    name = "Education"
    url = "#education"
    weight = 5

    [[menu.nav]]
    identifier = "contact"
    name = "Contact"
    url = "#contact"
    weight = 6